version: 2
jobs:
  test:
    machine:
      image: circleci/classic:latest
      environment:
        GO111MODULE: "on"
    steps:  
      - add_ssh_keys:
          fingerprints:
            - "56:7f:55:57:4e:bf:c6:70:b2:d7:43:ff:0f:6f:48:db"
      - checkout
      - run:
          name: Install golang
          command: |
            sudo rm -rf /usr/local/go
            wget -c https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.12.5.linux-amd64.tar.gz
            export PATH=$PATH:/usr/local/go/bin
      - run:
          name: Download dependencies
          command: go mod download
      - run:
          name: Run tests
          command: go test -v ./...
  publish:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "56:7f:55:57:4e:bf:c6:70:b2:d7:43:ff:0f:6f:48:db"
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            TAG=0.0.$CIRCLE_BUILD_NUM
            docker build -t romanyx/home:$TAG -f docker/Dockerfile .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            TAG=0.0.$CIRCLE_BUILD_NUM
            docker tag romanyx/home:$TAG romanyx/home:latest
            docker login -u=$DOCKERHUB_USER -p=$DOCKERHUB_PASSWORD
            docker push romanyx/home
  
workflows:
  version: 2
  test_and_publish:
    jobs:
      - test
      - publish:
          context: docker-hub
          requires:
            - test
          filters:
            branches:
              only: master


